version: '0.0.1'
services:
  db:
    hostname: db
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: password # https://github.com/psequel/psequel/issues/221#issuecomment-934450546
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - '15432:5432'
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: '10k'
        max-file: '5'
