export const guestList = [
  { name: 'shoji-mitsuhata', id: 'shoji-mitsuhata', created_at: new Date() },
  {
    name: 'hiroyuki-mitsuhata',
    id: 'hiroyuki-mitsuhata',
    created_at: new Date(),
  },
  {
    name: 'hiroyuki-tanizawa',
    id: 'hiroyuki-tanizawa',
    created_at: new Date(),
  },
  { name: 'emiko-tanizawa', id: 'emiko-tanizawa', created_at: new Date() },
  { name: 'sara-hosokawa', id: 'sara-hosokawa', created_at: new Date() },
  { name: 'lynne-onishi', id: 'lynne-onishi', created_at: new Date() },
  { name: 'maki-sasada', id: 'maki-sasada', created_at: new Date() },
  { name: 'asuka-okamoto', id: 'asuka-okamoto', created_at: new Date() },
  { name: 'mizuki-osaragi', id: 'mizuki-osaragi', created_at: new Date() },
  { name: 'erina-iwata', id: 'erina-iwata', created_at: new Date() },
  { name: 'koto-tamura', id: 'koto-tamura', created_at: new Date() },
  { name: 'ayano-sato', id: 'ayano-sato', created_at: new Date() },
  { name: 'yuzuka-tokui', id: 'yuzuka-tokui', created_at: new Date() },
  { name: 'sakura-okada', id: 'sakura-okada', created_at: new Date() },
  { name: 'tsukasa-watanabe', id: 'tsukasa-watanabe', created_at: new Date() },
  { name: 'kotono-shimoda', id: 'kotono-shimoda', created_at: new Date() },
  { name: 'wakako-geshi', id: 'wakako-geshi', created_at: new Date() },
  { name: 'yukari-sendayama', id: 'yukari-sendayama', created_at: new Date() },
  { name: 'izumi-fujisawa', id: 'izumi-fujisawa', created_at: new Date() },
  {
    name: 'reika-sakurabayashi',
    id: 'reika-sakurabayashi',
    created_at: new Date(),
  },
  { name: 'mika-tamura', id: 'mika-tamura', created_at: new Date() },
  { name: 'haruna-kawada', id: 'haruna-kawada', created_at: new Date() },
  { name: 'kurumi-kajiyama', id: 'kurumi-kajiyama', created_at: new Date() },
  { name: 'hitomi-wada', id: 'hitomi-wada', created_at: new Date() },
  { name: 'rikako-hagiwara', id: 'rikako-hagiwara', created_at: new Date() },
  { name: 'masao-nakano', id: 'masao-nakano', created_at: new Date() },
  { name: 'chieko-nakano', id: 'chieko-nakano', created_at: new Date() },
  { name: 'riko-nakano', id: 'riko-nakano', created_at: new Date() },
  { name: 'yutaro-shigeta', id: 'yutaro-shigeta', created_at: new Date() },
  { name: 'naoya-hatakeyama', id: 'naoya-hatakeyama', created_at: new Date() },
  { name: 'kohei-takigawa', id: 'kohei-takigawa', created_at: new Date() },
  { name: 'keitaro-komori', id: 'keitaro-komori', created_at: new Date() },
  { name: 'kiwamu-shiraiwa', id: 'kiwamu-shiraiwa', created_at: new Date() },
  { name: 'hiroyuki-ozawa', id: 'hiroyuki-ozawa', created_at: new Date() },
  { name: 'hikaru-nagao', id: 'hikaru-nagao', created_at: new Date() },
  { name: 'ryohei-tani', id: 'ryohei-tani', created_at: new Date() },
  { name: 'takaya-taniguchi', id: 'takaya-taniguchi', created_at: new Date() },
  { name: 'yoichi-ito', id: 'yoichi-ito', created_at: new Date() },
  { name: 'kaho-ito', id: 'kaho-ito', created_at: new Date() },
  {
    name: 'yoshitaka-miyamoto',
    id: 'yoshitaka-miyamoto',
    created_at: new Date(),
  },
  { name: 'shu-fukuoka', id: 'shu-fukuoka', created_at: new Date() },
  { name: 'keisuke-shibata', id: 'keisuke-shibata', created_at: new Date() },
  { name: 'satoshi-noguchi', id: 'satoshi-noguchi', created_at: new Date() },
  { name: 'toru-senba', id: 'toru-senba', created_at: new Date() },
  { name: 'yuichi-ishikawa', id: 'yuichi-ishikawa', created_at: new Date() },
  { name: 'keisuke-mizutani', id: 'keisuke-mizutani', created_at: new Date() },
  { name: 'tatsuya-osaka', id: 'tatsuya-osaka', created_at: new Date() },
];
